# This file was generated by GoReleaser. DO NOT EDIT.
cask "intentions" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "279be974addeaf1b22ff35e08b0ccaeae28726e5f4a05df45589f892a2b66a5d"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4365e0da65f94f4e9c083fff8ac38bc1c4c4685b9ae56f366ba7da75ec2b57ac"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "82d6a597699186ba79d2ef44341284ae99811835ce6113f6094864998dfaee37"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b4cc47e6ecefb9790b2dd231206f1cb9c14c63f16445664eb5668533cec4d43"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_linux_amd64.tar.gz"
    end
  end

  name "intentions"
  desc "Write and check Intentions Format workspaces from the command line"
  homepage "https://github.com/nodelogicau/intentions-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intentions"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intentions"]
    end
  end

  # No zap stanza required
end
