# This file was generated by GoReleaser. DO NOT EDIT.
cask "intentions" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "485a64f6165083851089465a02dfe951328f2c380a204b8af08425d6b0caf12e"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "60fe921e9b34650f4f8c8c0fdaeaf2bbd4c66c59f183863a5b06f0d40a37a424"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "73a6c215e500d97198e570b614332eac51681750ee27b98e8a024001814f3580"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "269ace5be26c4e1cb5c89b03f1f949cb86d3c13a792a02103cae474a73938b86"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_linux_amd64.tar.gz"
    end
  end

  name "intentions"
  desc "Write and check Intentions Format workspaces from the command line"
  homepage "https://github.com/nodelogicau/intentions-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intentions"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intentions"]
    end
  end

  # No zap stanza required
end
