# This file was generated by GoReleaser. DO NOT EDIT.
cask "intentions" do
  version "0.11.1"

  on_macos do
    on_arm do
      sha256 "2a19887e44d2173b6a8ae7ae58a15407020d8a2da585bff79c82e7cce9f9a599"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eaa9672f2dd76d7bda6ef2bd90c57be7cbcc16f8cf19573d114cc521c4c1a5a8"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "69e0f36e12d30d4df2e842fd464567bde43da5f2d666f4215c0f114f91437aa7"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b04d80b965e85fd8c46bfda284cb05452cf6b810bcaacfedc50ba8bec794011"
      url "https://github.com/nodelogicau/intentions-cli/releases/download/v#{version}/intentions_#{version}_linux_amd64.tar.gz"
    end
  end

  name "intentions"
  desc "Write and check Intentions Format workspaces from the command line"
  homepage "https://github.com/nodelogicau/intentions-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intentions"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/intentions"]
    end
  end

  # No zap stanza required
end
