# This file was generated by GoReleaser. DO NOT EDIT.
cask "particulars" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6a11ba6dd4f96a9a80dec05aa3ebf6e0e315e5a5686ff47fb6b38b5827131318"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
    on_arm do
      sha256 "02a509d9cc71397f126f2fea43ab19b2a02860c0af96f797b076522fa160b90f"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b27c4ed5004669843f40d724abd41574f5ddd447dca95c7a89c8342b4c32233e"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_linux_amd64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
    on_arm do
      sha256 "cbeef83641cd373524db7911e3db57192dde13ba010ad6b198447d73b0470a91"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_linux_arm64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
  end

  name "particulars"
  desc "Capture and recall dialectical knowledge (DKF) from the command line"
  homepage "https://github.com/nodelogicau/particulars-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "particulars"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/particulars"]
    end
  end

  # No zap stanza required

end
