# This file was generated by GoReleaser. DO NOT EDIT.
cask "particulars" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "2aa0b4b4f00c4e225afb1fd0272130a7145ffbd295fb2635f5f050dc6e4048aa"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
    on_intel do
      sha256 "389d93a622a2d25176a4670b74d581e35bc3717944034ed82dd1daaf0e4d2220"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
  end
  on_linux do
    on_arm do
      sha256 "0dfa5bb2925b87e41028e020fc661148c21ae19519050b6761f5ad31dab827d5"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_linux_arm64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
    on_intel do
      sha256 "2120ffd8fbc9783140ad979bb4ebb5c4b235fe3c67bbe257e5e4c1bd1a4df3de"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_linux_amd64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
  end

  name "particulars"
  desc "Capture and recall dialectical knowledge (DKF) from the command line"
  homepage "https://github.com/nodelogicau/particulars-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "particulars"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/particulars"]
    end
  end

  # No zap stanza required
end
