# This file was generated by GoReleaser. DO NOT EDIT.
cask "particulars" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "f70b4200c3f493d226509f92a748a17d921bfaf584993e50ccbdbee564692b4e"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
    on_arm do
      sha256 "e7c58d33b36eca66594da8f3ad68f613c3769eecb0aac5a192d26669a48d7285"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "065de2d431d3fad29569d104df3f501ad4f7f22310f419cfcaa2ccbc76effd6a"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_linux_amd64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
    on_arm do
      sha256 "6e224b9110582b808dd456b8753b3f77d1adc544e0d7f165ff53dbdebf039767"
      url "https://github.com/nodelogicau/particulars-cli/releases/download/v#{version}/particulars_#{version}_linux_arm64.tar.gz",
        verified: "github.com/nodelogicau/particulars-cli/"
    end
  end

  name "particulars"
  desc "Capture and recall dialectical knowledge (DKF) from the command line"
  homepage "https://github.com/nodelogicau/particulars-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "particulars"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/particulars"]
    end
  end

  # No zap stanza required

end
